#!/bin/sh

path="`dirname "$0"`"
bspace="$path/../bspace.py"

for arg in "" -rpython -roptimised
do
    echo arg=$arg
    
    echo "  Test basic arithmetic"
    $bspace $arg $path/count.ws | diff $path/count.out -
    
    echo "  Test printable-input mode"
    $bspace -iprintable $arg $path/count.wsp | diff $path/count.out -
    
    echo "  Test reading/writing characters"
    echo Chris | $bspace $arg $path/name.ws | diff $path/name.out -
    
    echo "  Test reading/writing numbers"
    echo 4 | $bspace $arg $path/hanoi.ws | diff $path/hanoi.out -
    
    echo "  Test Copy/Slide instructions"
    printf "123\n456\n" | $bspace $arg $path/loctest.ws | diff $path/loctest.out -
done

echo Test disassembler
$bspace -cassembly $path/loctest.ws | diff $path/loctest.wsa -

echo Test assembler
$bspace -iassembly -cwhitespace $path/hanoi.wsa | diff $path/hanoi.ws -

echo Test printable assembler
$bspace -iassembly -cprintable $path/hanoi.wsa | diff $path/hanoi.wsp -
